  
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-configmap
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: config-volume
        mountPath: /also/path
  volumes:
    - name: config-volume
      configMap:
        name: another-config 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
