apiVersion: v1
kind: Pod
metadata:
  name: my-recourse-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes World! && sleep 36000' ]
    resources:
      
      requests:
        memory: "256Mi"
        cpu: "250m"

      limits:
        memory: "300Mi"
        cpu: "500m"
