apiVersion: v1
kind: Pod
metadata: 
  name: my-secreted-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo example pod && sleep 3600"]
    env:
    - name: MY_VAR
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: mykey 
