apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-resources
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: "60Mi"
        cpu: "40m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
